language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
before_install:
  - julia -e 'Pkg.add("Distributions")'
  - julia -e 'Pkg.add("Mimi")'
script:
  - julia test/runtests.jl
